src/App.tsx, src/components/views/Landing/Landing.tsx
Le agregué la navbar que hizo Gastón al landing
=> refactor(landing): added navbar

src/App.css
=> refactor/App.css: global variables

src/components/commons/HomeContent/HomeContent.tsx, src/redux/reducer/index.ts
A modo de ejemplo. El botón del Home despacha una función que carga el store para poder acceder a la data de géneros.
=> fix(/Home): Redux funcionando

src/components/commons/ContentAlbumPlaylist/ContentAlbumPlaylist.tsx, src/consts/sw_types.d.ts, tsconfig.json
no hace falta importar los tipos, solo escriben y autocompleta:
swAlbum
swArtist
swSong
swPlaylist
swGenre
swUse
=> fix(): global types

src/components/commons/Player/Player.jsx, src/components/commons/Player/Player.module.css
ya quedó listo para recibir la info de redux, hago el pr antes de hacer las actions porque toque el reducer y se me rompio (no lo subo)
=> refactor(player): changed styles and variable names

src/components/commons/CardContainer/CardContainer.tsx, src/redux/actions/types.ts
en card container habia un map que rompia, le agregue el signo de preguntas
en las actions types faltaba inportar las types
=> fixed/cardContainer & action tipes

package.json, src/components/commons/CardsComponents/ItemList/ItemList.tsx, src/components/commons/LoginForm/LoginForm.module.css, src/components/commons/LoginForm/LoginForm.tsx, src/components/commons/SignUpForm/SignUpForm.module.css, src/components/commons/SignUpForm/SignUpForm.tsx, src/components/views/SearchResults/SearchResults.tsx, src/redux/reducer/index.ts
ya esta el form con estilos y mejor descripción de los campos
=> Fixed(/search results)

src/components/commons/CardItem/CardItem.module.css, src/components/commons/CardItem/CardItem.tsx, src/components/commons/CardsComponents/ItemList/ItemList.module.css, src/components/commons/CardsComponents/ItemList/ItemList.tsx, src/components/commons/DropDownButton/DropDownButton.tsx, src/components/commons/Player/Player.jsx, src/redux/actions/action_player.ts, src/redux/actions/types.ts
known bug: cuando pasas de una vista a otra se reinicia la canción, voy a ver como arreglarlo
=> fix(player): added playing capabilities to cards and listitems

src/components/commons/ContainerLibrary/ContainerLibrary.tsx, src/components/views/Genre/Genre.tsx
borré dos lineas que no se usaban
=> fix(cardItem)

src/components/commons/NavBar/NavBar.tsx, src/components/commons/SearchBar/MenuUser.tsx, src/components/commons/SearchBar/SearchBar.tsx, src/components/views/FileUpload/FileUpload.tsx, src/components/views/Landing/Landing.tsx, src/index.tsx
se modifico toda la funcionalidad del login
=> Cristian front2

package.json, src/components/commons/ContentAlbumPlaylist/ContentAlbumPlaylist.tsx, src/components/commons/ListItemContainer/ListItem.module.css, src/components/commons/ListItemContainer/ListItem.tsx, src/components/commons/ListItemContainer/ListItemContainer.tsx
que da pendiente lo de playlist
=> refactor(album_playlist)

src/components/commons/UserCardAdmin/UserCardAdmin.tsx
=> ya se puede aceptar solicitudes para ser artista

src/redux/reducer/index.ts
al reducer le faltaba un } y se rompia totalmente
=> fix(reducer)

src/components/commons/DropDownButton/DropDownButton.tsx
evaluen bien los cambios porfa
=> parentesis

src/components/commons/CardContainer/CardContainer.tsx, src/components/commons/FavoriteIcon/FavoriteIcon.tsx, src/components/commons/PanelArtist/PanelArtistProfile.tsx, src/components/views/PanelArtist/PanelArtist.tsx, src/redux/actions/action_artist.ts, src/redux/reducer/index.ts
=> fix(PanelArtist): new info works

src/components/commons/ListItemContainer/ListItemContainer.tsx, src/components/commons/PanelArtist/PanelArtistProfile.tsx, src/components/commons/PanelArtist/PanelArtistSongs.tsx, src/redux/actions/action_artist.ts, src/redux/actions/types.ts, src/redux/reducer/index.ts
=> fix(PanelArtist):

src/components/commons/CardContainer/CardItem.tsx, src/components/commons/CardsComponents/ItemList/ItemList.tsx, src/components/commons/ContentHome/ContentHome.tsx, src/components/commons/ListItemContainer/ListItem.tsx, src/components/commons/PanelArtist/ContainerList/ListItem.tsx, src/components/commons/TopPage/TopCard.tsx, src/components/views/Landing/Landing.tsx, src/redux/actions/action_player.ts, src/redux/actions/types.ts, src/redux/reducer/index.ts, src/redux/reducer/types.ts
lo importante es la intencion xd
=> incremental playcount + recently played

src/components/commons/ArtistPage/ArtistCardContainer/ArtistCardContainer.tsx, src/components/commons/ArtistPage/ArtistPage.tsx, src/components/commons/ListItemContainer/ListItem.tsx, src/components/commons/PanelArtist/PanelArtistProfile.tsx, src/redux/reducer/index.ts
=> donation history in artist page and artist panel

src/components/commons/NavBar/NavBar.tsx
=> avatar from db on landing

src/components/views/UserSettings/UserSettings.tsx
=> donation history in user settings

src/assets/pencil.svg, src/components/commons/PanelArtist/PanelArtistProfile.tsx
=> fix(PanelArtist): svg error

src/redux/reducer/index.ts
Se arreglo para que no se  agregen canciones repetidas a la queue
=> fix(QueuPanel): dont added to the queue repeat songs
